config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'boards#index'

  resources :boards
  get "/webhooks/receive", to: "webhooks#complete"
  post "/webhooks/receive", to: "webhooks#receive"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ActiveRecord::Base
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    board = Trello::Member.find('mamadikabelo').boards.first
    @board_name = board.name
    @lists = board.lists
    @cards = board.cards
    list_id = @lists.first.id
    # webhook_details = create_webhook(list_id)
    # Trello::Webhook.create(trello_id: webhook_details['id'],
    #                        active: true,
    #                        callback_url: webhook_details['callbackURL'],
    #                        board_id: board.id,
    #                        trello_model_type: 'Board')
  end

  def new
    @card = Card.new
  end

  def create
    member = Trello::Member.find('mamadikabelo')
    list_id = member.boards.first.lists.first.id
    card = Card.create!(list_id: list_id, name: card_params[:name])

    card = Trello::Card.create(
      name: card.name,
      list_id: card.list_id,
      member_ids: [ member.id ]
    )
    redirect_to root_path
  end

  def create_webhook(trello_board_id)
    member = Trello::Member.find('mamadikabelo')
    list = member.boards.first.lists.first
    list_id = list.id
    url = 'https://49ca-160-19-36-2.ngrok.io'
    developer_public_key = '2351e84812a80d260e9c7893fedd7864'
    member_token = 'b14ed13ffc35d84ca18d60e6b505db23d818173d0064ecfeb0f35b9da1515141'
    # HTTParty.post("https://api.trello.com/1/tokens/#{member_token}/webhooks/?key=#{developer_public_key}",
    #               query: { callbackURL: url, idModel: list_id },
    #               headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    #               timeout: 35)
  end

  private

  def card_params
    params.require(:card).permit(:id, :name, :list_id)
  end

end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_before_action :authenticate
  skip_before_action :verify_authenticity_token

  def complete; end

  def receive; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/index.html.erb
<h2 style="background-color:#343951; color:white; text-align: center"> <%= @board_name %> </h2>
<div style="background-color:#F3F4F5">
  <% @lists.each do |list| %>
    <table>
      <thead>
        <th width="15%"><%= list.name %> </th>
      </thead>
      <tbody>
      <% @cards.each do |card| %>
        <% if card.list_id == list.id %>
          <tr>
            <td align="center"><%= card.name %></td>
          </tr>
        <% end%>
      <% end%>
      </tbody>
    </table>
  <br/>
  <% end %>

  <br/>
  <%= link_to 'Add new card', new_board_path%>
</div>

app/views/boards/new.html.erb
<%= form_for @card, method: :post, url: boards_path do |f| %>
  <h2> New Card</h2>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </div>
  <br/>
  <%= f.submit "Create Card" %>
<% end %>
<br/>
<%= link_to 'Back', root_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzaProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:#F3F4F5">
    <%= yield %>
  </body>
</html>